[package]
name = "fraction NFT"
version = "1.0.0"

[addresses]
aptos_framework = "0x1"
fractionNFT="_"
source_addr="_"



[dependencies]
AptosFramework={git = "https://github.com/aptos-labs/aptos-core.git",subdir = "aptos-move/framework/aptos-framework",rev = "devnet"}
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev="devnet"}
