[package]
name = "INFINITY"
version = "1.0.0"

[addresses]
resource_addr="4d3759b50d7fa0d64d1743a409b1313f04d8cad51530f7f4af6294e33fc2f6e0"


[dependencies]
InfinityCoin = {local = "D:/Metapolis/aptos/infinity-coin/"}
AptosFramework={git = "https://github.com/aptos-labs/aptos-core.git",subdir = "aptos-move/framework/aptos-framework",rev = "devnet"}
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev="devnet"}
